Fixed installer for generated files on Windows
google/bazel_rules_install pull request #33
Opened 2021-11-16 03:10 UTC by corco

Installer would fail if the file was generated by bazel on Windows.

A generated file was added to the testsuite and a fix was implemented

2021-11-16 21:46 UTC, bttk requested changes
Thanks for the patch! I have only some style comments.

2021-11-16 21:46 UTC, bttk commented on tests/BUILD.bazel
> +    name = "generate_test",
Could you change this name to '"generated_file"' ?

2021-11-16 21:46 UTC, bttk commented on tests/BUILD.bazel
> +    data = ["generated_file.txt"],
```
data = [":generated_file"],
```

https://docs.bazel.build/versions/main/skylark/build-style.html#references-to-targets-in-the-current-package

Same below (L97, L101)

2021-11-17 02:55 UTC, bttk approved these changes

2021-11-17 02:57 UTC, merged

2021-11-17 04:23 UTC, bttk commented
@corco let me know if you'd like an entry in the AUTHORS file. If so, what should the entry say?

2021-11-17 20:22 UTC, corco commented
Sure, you can list me as "Jonathan Drolet <jonathan.drolet@gmail.com>"